{{- if .Values.billing.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "billing.secretName" . }}
  labels:
    {{- include "billing.labels" . | nindent 4 }}
type: Opaque
stringData:
  clickhouse-username: {{ .Values.billing.secrets.clickhouseUsername | quote }}
  clickhouse-password: {{ .Values.billing.secrets.clickhousePassword | quote }}
  postgres-dsn: {{ .Values.billing.secrets.postgresDsn | quote }}
  management-shared-secret: {{ .Values.billing.secrets.managementSharedSecret | quote }}
{{- end }}
