apiVersion: v1
kind: Service
metadata:
  name: {{ include "billing.fullname" . }}
  labels:
    {{- include "billing.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "billing.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.billing.port }}
      targetPort: http
