import {
  AbbrApi,
  Bell,
  BookOpen,
  Boxes3,
  Briefcase,
  ChartLine,
  CircleDollar,
  Cloud,
  Cubes3,
  Database,
  FaceRobot,
  FileText,
  Folder,
  Gear,
  GearBranches,
  House,
  Key,
  Layers3Diagonal,
  ListCheckLock,
  Magnifier,
  Person,
  PersonMagnifier,
  Persons,
  PersonsLock,
  Play,
  PlugConnection,
  Pulse,
  Rocket,
  Route,
  ScalesBalanced,
  Server,
  Shield,
  ShieldKeyhole,
  Sparkles,
  Tag,
  TagDollar,
} from "@gravity-ui/icons";
import type { AsideHeaderItem } from "@gravity-ui/navigation/build/esm/index.js";
import type { AppRoute } from "./routes";

export const navigationGroups: AppRoute["group"][] = ["Manage", "Monitor", "Access Control", "AI Hub", "Govern", "System"];

const routeIcons: Record<string, NonNullable<AsideHeaderItem["icon"]>> = {
  "/api-keys": Key,
  "/models": Cubes3,
  "/model-onboarding": Rocket,
  "/providers": Cloud,
  "/credentials": ShieldKeyhole,
  "/deployments": Server,
  "/model-groups": Layers3Diagonal,
  "/overview": House,
  "/usage": ChartLine,
  "/customers": PersonMagnifier,
  "/logs": FileText,
  "/routing": Route,
  "/playground": Play,
  "/organizations": Briefcase,
  "/teams": Persons,
  "/users": Person,
  "/access-groups": PersonsLock,
  "/projects": Folder,
  "/ai-hub": Sparkles,
  "/cost-optimization": TagDollar,
  "/mcp-servers": PlugConnection,
  "/mcp-toolsets": Boxes3,
  "/tool-policies": ListCheckLock,
  "/agents": FaceRobot,
  "/search-tools": Magnifier,
  "/skills": BookOpen,
  "/guardrails": Shield,
  "/guardrails-monitor": Pulse,
  "/budgets": CircleDollar,
  "/policies": ScalesBalanced,
  "/tag-management": Tag,
  "/cache": Database,
  "/logging": Bell,
  "/router-settings": GearBranches,
  "/api-reference": AbbrApi,
  "/settings": Gear,
};

export function navigationIcon(path: string): NonNullable<AsideHeaderItem["icon"]> {
  return routeIcons[path] || Sparkles;
}
