package gateway

import (
	"net/http"

	"go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
)

type RouteContract struct {
	Method string
	Path   string
}

type routeDefinition struct {
	RouteContract
	handler func(Handler) http.Handler
}

var gatewayRoutes = []routeDefinition{
	{RouteContract{http.MethodGet, "/healthz"}, func(h Handler) http.Handler { return http.HandlerFunc(h.Health) }},
	{RouteContract{http.MethodGet, "/readyz"}, func(h Handler) http.Handler { return http.HandlerFunc(h.Ready) }},
	{RouteContract{http.MethodGet, "/metrics"}, func(h Handler) http.Handler { return h.metrics }},
	{RouteContract{http.MethodGet, "/auth/sso/config"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetBrowserSSOConfig) }},
	{RouteContract{http.MethodGet, "/auth/sso/start"}, func(h Handler) http.Handler { return http.HandlerFunc(h.StartBrowserSSO) }},
	{RouteContract{http.MethodGet, "/auth/sso/callback"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CompleteBrowserSSO) }},
	{RouteContract{http.MethodPost, "/auth/sso/logout"}, func(h Handler) http.Handler { return http.HandlerFunc(h.EndBrowserSSO) }},
	{RouteContract{http.MethodGet, "/scim/v2"}, func(h Handler) http.Handler { return http.HandlerFunc(h.SCIMBase) }},
	{RouteContract{http.MethodGet, "/scim/v2/ServiceProviderConfig"}, func(h Handler) http.Handler { return http.HandlerFunc(h.SCIMServiceProviderConfig) }},
	{RouteContract{http.MethodGet, "/scim/v2/ResourceTypes"}, func(h Handler) http.Handler { return http.HandlerFunc(h.SCIMResourceTypes) }},
	{RouteContract{http.MethodGet, "/scim/v2/ResourceTypes/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.SCIMResourceType) }},
	{RouteContract{http.MethodGet, "/scim/v2/Schemas"}, func(h Handler) http.Handler { return http.HandlerFunc(h.SCIMSchemas) }},
	{RouteContract{http.MethodGet, "/scim/v2/Schemas/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.SCIMSchema) }},
	{RouteContract{http.MethodGet, "/scim/v2/Users"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListSCIMUsers) }},
	{RouteContract{http.MethodPost, "/scim/v2/Users"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CreateSCIMUser) }},
	{RouteContract{http.MethodGet, "/scim/v2/Users/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetSCIMUser) }},
	{RouteContract{http.MethodPut, "/scim/v2/Users/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ReplaceSCIMUser) }},
	{RouteContract{http.MethodPatch, "/scim/v2/Users/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.PatchSCIMUser) }},
	{RouteContract{http.MethodDelete, "/scim/v2/Users/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteSCIMUser) }},
	{RouteContract{http.MethodGet, "/scim/v2/Groups"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListSCIMGroups) }},
	{RouteContract{http.MethodPost, "/scim/v2/Groups"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CreateSCIMGroup) }},
	{RouteContract{http.MethodGet, "/scim/v2/Groups/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetSCIMGroup) }},
	{RouteContract{http.MethodPut, "/scim/v2/Groups/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ReplaceSCIMGroup) }},
	{RouteContract{http.MethodPatch, "/scim/v2/Groups/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.PatchSCIMGroup) }},
	{RouteContract{http.MethodDelete, "/scim/v2/Groups/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteSCIMGroup) }},
	{RouteContract{http.MethodGet, "/v1/models"}, func(h Handler) http.Handler { return http.HandlerFunc(h.Models) }},
	{RouteContract{http.MethodGet, "/v1/models/{model}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetModel) }},
	{RouteContract{http.MethodPost, "/v1/assistants"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CreateAssistant) }},
	{RouteContract{http.MethodGet, "/v1/assistants"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListAssistants) }},
	{RouteContract{http.MethodGet, "/v1/assistants/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetAssistant) }},
	{RouteContract{http.MethodPost, "/v1/assistants/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.UpdateAssistant) }},
	{RouteContract{http.MethodDelete, "/v1/assistants/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteAssistant) }},
	{RouteContract{http.MethodPost, "/v1/threads"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CreateAssistantThread) }},
	{RouteContract{http.MethodGet, "/v1/threads/{thread_id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetAssistantThread) }},
	{RouteContract{http.MethodPost, "/v1/threads/{thread_id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.UpdateAssistantThread) }},
	{RouteContract{http.MethodDelete, "/v1/threads/{thread_id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteAssistantThread) }},
	{RouteContract{http.MethodPost, "/v1/threads/{thread_id}/messages"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CreateAssistantMessage) }},
	{RouteContract{http.MethodGet, "/v1/threads/{thread_id}/messages"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListAssistantMessages) }},
	{RouteContract{http.MethodGet, "/v1/threads/{thread_id}/messages/{message_id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetAssistantMessage) }},
	{RouteContract{http.MethodPost, "/v1/threads/{thread_id}/messages/{message_id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.UpdateAssistantMessage) }},
	{RouteContract{http.MethodDelete, "/v1/threads/{thread_id}/messages/{message_id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteAssistantMessage) }},
	{RouteContract{http.MethodPost, "/v1/threads/{thread_id}/runs"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CreateAssistantRun) }},
	{RouteContract{http.MethodGet, "/v1/threads/{thread_id}/runs"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListAssistantRuns) }},
	{RouteContract{http.MethodGet, "/v1/threads/{thread_id}/runs/{run_id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetAssistantRun) }},
	{RouteContract{http.MethodPost, "/v1/threads/{thread_id}/runs/{run_id}/cancel"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CancelAssistantRun) }},
	{RouteContract{http.MethodPost, "/v1/threads/{thread_id}/runs/{run_id}/submit_tool_outputs"}, func(h Handler) http.Handler { return http.HandlerFunc(h.SubmitAssistantRunToolOutputs) }},
	{RouteContract{http.MethodGet, "/v1/threads/{thread_id}/runs/{run_id}/steps"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListAssistantRunSteps) }},
	{RouteContract{http.MethodGet, "/v1/threads/{thread_id}/runs/{run_id}/steps/{step_id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetAssistantRunStep) }},
	{RouteContract{http.MethodDelete, "/v1/models/{model}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteFineTunedModel) }},
	{RouteContract{http.MethodGet, "/a2a/{agent}/.well-known/agent-card.json"}, func(h Handler) http.Handler { return http.HandlerFunc(h.A2AAgentCard) }},
	{RouteContract{http.MethodPost, "/a2a/{agent}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.A2AJSONRPC) }},
	{RouteContract{http.MethodPost, "/model/{model}/converse"}, func(h Handler) http.Handler { return http.HandlerFunc(h.BedrockConverse) }},
	{RouteContract{http.MethodPost, "/model/{model}/converse-stream"}, func(h Handler) http.Handler { return http.HandlerFunc(h.BedrockConverseStream) }},
	{RouteContract{http.MethodPost, "/model/{model}/invoke"}, func(h Handler) http.Handler { return http.HandlerFunc(h.BedrockInvoke) }},
	{RouteContract{http.MethodPost, "/model/{model}/invoke-with-response-stream"}, func(h Handler) http.Handler { return http.HandlerFunc(h.BedrockInvokeStream) }},
	{RouteContract{http.MethodPost, "/v1/chat/completions"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ChatCompletions) }},
	{RouteContract{http.MethodPost, "/v1/completions"}, func(h Handler) http.Handler { return http.HandlerFunc(h.Completions) }},
	{RouteContract{http.MethodPost, "/v1/messages"}, func(h Handler) http.Handler { return http.HandlerFunc(h.Messages) }},
	{RouteContract{http.MethodPost, "/v1/messages/count_tokens"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CountMessageTokens) }},
	{RouteContract{http.MethodPost, "/v1/messages/batches"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CreateMessagesBatch) }},
	{RouteContract{http.MethodGet, "/v1/messages/batches"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListMessagesBatches) }},
	{RouteContract{http.MethodGet, "/v1/messages/batches/{message_batch_id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetMessagesBatch) }},
	{RouteContract{http.MethodPost, "/v1/messages/batches/{message_batch_id}/cancel"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CancelMessagesBatch) }},
	{RouteContract{http.MethodDelete, "/v1/messages/batches/{message_batch_id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteMessagesBatch) }},
	{RouteContract{http.MethodGet, "/v1/messages/batches/{message_batch_id}/results"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetMessagesBatchResults) }},
	{RouteContract{http.MethodPost, "/v1/responses"}, func(h Handler) http.Handler { return http.HandlerFunc(h.Responses) }},
	{RouteContract{http.MethodGet, "/v1/realtime"}, func(h Handler) http.Handler { return http.HandlerFunc(h.Realtime) }},
	{RouteContract{http.MethodPost, "/v1/interactions"}, func(h Handler) http.Handler { return http.HandlerFunc(h.Interactions) }},
	{RouteContract{http.MethodGet, "/v1/interactions/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetInteraction) }},
	{RouteContract{http.MethodDelete, "/v1/interactions/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteInteraction) }},
	{RouteContract{http.MethodPost, "/v1/interactions/{id}/cancel"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CancelInteraction) }},
	{RouteContract{http.MethodPost, "/v1/responses/input_tokens"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CountResponseInputTokens) }},
	{RouteContract{http.MethodPost, "/v1/responses/compact"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CompactResponse) }},
	{RouteContract{http.MethodGet, "/v1/responses/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetResponse) }},
	{RouteContract{http.MethodDelete, "/v1/responses/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteResponse) }},
	{RouteContract{http.MethodPost, "/v1/responses/{id}/cancel"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CancelResponse) }},
	{RouteContract{http.MethodGet, "/v1/responses/{id}/input_items"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListResponseInputItems) }},
	{RouteContract{http.MethodPost, "/v1/embeddings"}, func(h Handler) http.Handler { return http.HandlerFunc(h.Embeddings) }},
	{RouteContract{http.MethodPost, "/v1/rerank"}, func(h Handler) http.Handler { return http.HandlerFunc(h.Rerank) }},
	{RouteContract{http.MethodPost, "/v1/moderations"}, func(h Handler) http.Handler { return http.HandlerFunc(h.Moderations) }},
	{RouteContract{http.MethodPost, "/v1/images/generations"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GenerateImage) }},
	{RouteContract{http.MethodPost, "/v1/images/edits"}, func(h Handler) http.Handler { return http.HandlerFunc(h.EditImage) }},
	{RouteContract{http.MethodPost, "/v1/images/variations"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CreateImageVariation) }},
	{RouteContract{http.MethodPost, "/v1/audio/transcriptions"}, func(h Handler) http.Handler { return http.HandlerFunc(h.TranscribeAudio) }},
	{RouteContract{http.MethodPost, "/v1/audio/translations"}, func(h Handler) http.Handler { return http.HandlerFunc(h.TranslateAudio) }},
	{RouteContract{http.MethodPost, "/v1/audio/speech"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GenerateSpeech) }},
	{RouteContract{http.MethodPost, "/v1/sandbox/execute"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ExecuteSandbox) }},
	{RouteContract{http.MethodPost, "/v1/files"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CreateFile) }},
	{RouteContract{http.MethodGet, "/v1/files"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListFiles) }},
	{RouteContract{http.MethodGet, "/v1/files/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetFile) }},
	{RouteContract{http.MethodDelete, "/v1/files/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteFile) }},
	{RouteContract{http.MethodGet, "/v1/files/{id}/content"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetFileContent) }},
	{RouteContract{http.MethodPost, "/v1/batches"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CreateBatch) }},
	{RouteContract{http.MethodGet, "/v1/batches"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListBatches) }},
	{RouteContract{http.MethodGet, "/v1/batches/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetBatch) }},
	{RouteContract{http.MethodPost, "/v1/batches/{id}/cancel"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CancelBatch) }},
	{RouteContract{http.MethodPost, "/v1/fine_tuning/jobs"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CreateFineTuningJob) }},
	{RouteContract{http.MethodPost, "/v1/videos"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CreateVideo) }},
	{RouteContract{http.MethodPost, "/v1/containers"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CreateContainer) }},
	{RouteContract{http.MethodGet, "/v1/containers"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListContainers) }},
	{RouteContract{http.MethodGet, "/v1/containers/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetContainer) }},
	{RouteContract{http.MethodDelete, "/v1/containers/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteContainer) }},
	{RouteContract{http.MethodPost, "/v1/containers/{id}/files"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CreateContainerFile) }},
	{RouteContract{http.MethodGet, "/v1/containers/{id}/files"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListContainerFiles) }},
	{RouteContract{http.MethodGet, "/v1/containers/{id}/files/{file_id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetContainerFile) }},
	{RouteContract{http.MethodDelete, "/v1/containers/{id}/files/{file_id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteContainerFile) }},
	{RouteContract{http.MethodGet, "/v1/containers/{id}/files/{file_id}/content"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetContainerFileContent) }},
	{RouteContract{http.MethodGet, "/v1/videos"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListVideos) }},
	{RouteContract{http.MethodGet, "/v1/videos/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetVideo) }},
	{RouteContract{http.MethodDelete, "/v1/videos/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteVideo) }},
	{RouteContract{http.MethodGet, "/v1/videos/{id}/content"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetVideoContent) }},
	{RouteContract{http.MethodPost, "/v1/videos/{id}/remix"}, func(h Handler) http.Handler { return http.HandlerFunc(h.RemixVideo) }},
	{RouteContract{http.MethodPost, "/v1/videos/{id}/extend"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ExtendVideo) }},
	{RouteContract{http.MethodGet, "/v1/fine_tuning/jobs"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListFineTuningJobs) }},
	{RouteContract{http.MethodGet, "/v1/fine_tuning/jobs/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetFineTuningJob) }},
	{RouteContract{http.MethodPost, "/v1/fine_tuning/jobs/{id}/cancel"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CancelFineTuningJob) }},
	{RouteContract{http.MethodPost, "/v1/fine_tuning/jobs/{id}/pause"}, func(h Handler) http.Handler { return http.HandlerFunc(h.PauseFineTuningJob) }},
	{RouteContract{http.MethodPost, "/v1/fine_tuning/jobs/{id}/resume"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ResumeFineTuningJob) }},
	{RouteContract{http.MethodGet, "/v1/fine_tuning/jobs/{id}/events"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListFineTuningEvents) }},
	{RouteContract{http.MethodGet, "/v1/fine_tuning/jobs/{id}/checkpoints"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListFineTuningCheckpoints) }},
	{RouteContract{http.MethodPost, "/v1/vector_stores"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CreateVectorStore) }},
	{RouteContract{http.MethodGet, "/v1/vector_stores"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListVectorStores) }},
	{RouteContract{http.MethodGet, "/v1/vector_stores/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetVectorStore) }},
	{RouteContract{http.MethodPost, "/v1/vector_stores/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.UpdateVectorStore) }},
	{RouteContract{http.MethodDelete, "/v1/vector_stores/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteVectorStore) }},
	{RouteContract{http.MethodPost, "/v1/vector_stores/{id}/files"}, func(h Handler) http.Handler { return http.HandlerFunc(h.AttachVectorStoreFile) }},
	{RouteContract{http.MethodGet, "/v1/vector_stores/{id}/files"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListVectorStoreFiles) }},
	{RouteContract{http.MethodGet, "/v1/vector_stores/{id}/files/{file_id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetVectorStoreFile) }},
	{RouteContract{http.MethodPost, "/v1/vector_stores/{id}/files/{file_id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.UpdateVectorStoreFile) }},
	{RouteContract{http.MethodDelete, "/v1/vector_stores/{id}/files/{file_id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteVectorStoreFile) }},
	{RouteContract{http.MethodGet, "/v1/vector_stores/{id}/files/{file_id}/content"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetVectorStoreFileContent) }},
	{RouteContract{http.MethodPost, "/v1/vector_stores/{id}/file_batches"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CreateVectorStoreFileBatch) }},
	{RouteContract{http.MethodGet, "/v1/vector_stores/{id}/file_batches/{batch_id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetVectorStoreFileBatch) }},
	{RouteContract{http.MethodPost, "/v1/vector_stores/{id}/file_batches/{batch_id}/cancel"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CancelVectorStoreFileBatch) }},
	{RouteContract{http.MethodGet, "/v1/vector_stores/{id}/file_batches/{batch_id}/files"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListVectorStoreFileBatchFiles) }},
	{RouteContract{http.MethodPost, "/v1/vector_stores/{id}/search"}, func(h Handler) http.Handler { return http.HandlerFunc(h.SearchVectorStore) }},
	{RouteContract{http.MethodPost, "/v1/rag/ingest"}, func(h Handler) http.Handler { return http.HandlerFunc(h.RAGIngest) }},
	{RouteContract{http.MethodPost, "/v1/rag/query"}, func(h Handler) http.Handler { return http.HandlerFunc(h.RAGQuery) }},
	{RouteContract{http.MethodPost, "/v1/skills"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CreateSkill) }},
	{RouteContract{http.MethodGet, "/v1/skills"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListSkills) }},
	{RouteContract{http.MethodGet, "/v1/skills/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetSkill) }},
	{RouteContract{http.MethodPost, "/v1/skills/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.UpdateSkill) }},
	{RouteContract{http.MethodDelete, "/v1/skills/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteSkill) }},
	{RouteContract{http.MethodGet, "/v1/skills/{id}/content"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetSkillContent) }},
	{RouteContract{http.MethodPost, "/v1/skills/{id}/versions"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CreateSkillVersion) }},
	{RouteContract{http.MethodGet, "/v1/skills/{id}/versions"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListSkillVersions) }},
	{RouteContract{http.MethodGet, "/v1/skills/{id}/versions/{version}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetSkillVersion) }},
	{RouteContract{http.MethodDelete, "/v1/skills/{id}/versions/{version}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteSkillVersion) }},
	{RouteContract{http.MethodGet, "/v1/skills/{id}/versions/{version}/content"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetSkillVersionContent) }},
	{RouteContract{http.MethodPost, "/v1/search"}, func(h Handler) http.Handler { return http.HandlerFunc(h.Search) }},
	{RouteContract{http.MethodPost, "/v1/ocr"}, func(h Handler) http.Handler { return http.HandlerFunc(h.OCR) }},
	{RouteContract{http.MethodGet, "/v1/mcp/servers/{id}/tools"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListMCPServerTools) }},
	{RouteContract{http.MethodPost, "/v1/mcp/servers/{id}/tools/{tool}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CallMCPServerTool) }},
	{RouteContract{http.MethodPost, "/guardrails/apply_guardrail"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ApplyGuardrail) }},
	{RouteContract{http.MethodGet, "/admin/v1/session"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetAdminSession) }},
	{RouteContract{http.MethodGet, "/admin/v1/keys"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListVirtualKeys) }},
	{RouteContract{http.MethodPost, "/admin/v1/keys"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CreateVirtualKey) }},
	{RouteContract{http.MethodPost, "/admin/v1/keys/{id}/rotate"}, func(h Handler) http.Handler { return http.HandlerFunc(h.RotateVirtualKey) }},
	{RouteContract{http.MethodPut, "/admin/v1/keys/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.UpdateVirtualKey) }},
	{RouteContract{http.MethodPost, "/admin/v1/keys/{id}/disable"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DisableVirtualKey) }},
	{RouteContract{http.MethodPost, "/admin/v1/keys/{id}/enable"}, func(h Handler) http.Handler { return http.HandlerFunc(h.EnableVirtualKey) }},
	{RouteContract{http.MethodDelete, "/admin/v1/keys/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.RevokeVirtualKey) }},
	{RouteContract{http.MethodGet, "/admin/v1/users"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListDirectoryUsers) }},
	{RouteContract{http.MethodPut, "/admin/v1/users/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.PutDirectoryUser) }},
	{RouteContract{http.MethodGet, "/admin/v1/teams"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListDirectoryTeams) }},
	{RouteContract{http.MethodPut, "/admin/v1/teams/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.PutDirectoryTeam) }},
	{RouteContract{http.MethodPut, "/admin/v1/teams/{id}/members/{user_id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.PutTeamMembership) }},
	{RouteContract{http.MethodGet, "/admin/v1/teams/{id}/members"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListTeamMemberships) }},
	{RouteContract{http.MethodDelete, "/admin/v1/teams/{id}/members/{user_id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteTeamMembership) }},
	{RouteContract{http.MethodGet, "/admin/v1/organizations"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListOrganizations) }},
	{RouteContract{http.MethodPut, "/admin/v1/organizations/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.PutOrganization) }},
	{RouteContract{http.MethodPut, "/admin/v1/organizations/{id}/teams/{team_id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.PutOrganizationTeam) }},
	{RouteContract{http.MethodDelete, "/admin/v1/organizations/{id}/teams/{team_id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteOrganizationTeam) }},
	{RouteContract{http.MethodGet, "/admin/v1/budgets"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListBudgets) }},
	{RouteContract{http.MethodPost, "/admin/v1/budgets"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CreateBudget) }},
	{RouteContract{http.MethodGet, "/admin/v1/budgets/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetBudget) }},
	{RouteContract{http.MethodPut, "/admin/v1/budgets/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.UpdateBudget) }},
	{RouteContract{http.MethodDelete, "/admin/v1/budgets/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DisableBudget) }},
	{RouteContract{http.MethodGet, "/admin/v1/budgets/{id}/summary"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetBudgetSummary) }},
	{RouteContract{http.MethodGet, "/admin/v1/usage/report"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetUsageReport) }},
	{RouteContract{http.MethodGet, "/admin/v1/customers/{scope_type}/{scope_id}/usage"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetCustomerUsageReport) }},
	{RouteContract{http.MethodGet, "/admin/v1/request-logs"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListRequestLogs) }},
	{RouteContract{http.MethodGet, "/admin/v1/request-logs/groups"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListRequestLogGroups) }},
	{RouteContract{http.MethodGet, "/admin/v1/request-logs/settings"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetRequestLogSettings) }},
	{RouteContract{http.MethodGet, "/admin/v1/request-logs/{request_id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetRequestLog) }},
	{RouteContract{http.MethodGet, "/admin/v1/routing/diagnostics"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetRoutingDiagnostics) }},
	{RouteContract{http.MethodPost, "/admin/v1/routing/simulate"}, func(h Handler) http.Handler { return http.HandlerFunc(h.SimulateRouting) }},
	{RouteContract{http.MethodGet, "/admin/v1/model-catalog"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetModelCatalog) }},
	{RouteContract{http.MethodPost, "/admin/v1/model-onboarding/plan"}, func(h Handler) http.Handler { return http.HandlerFunc(h.PlanModelOnboarding) }},
	{RouteContract{http.MethodPost, "/admin/v1/model-onboarding/apply"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ApplyModelOnboarding) }},
	{RouteContract{http.MethodGet, "/admin/v1/providers"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListProviders) }},
	{RouteContract{http.MethodGet, "/admin/v1/provider-capabilities"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListProviderCapabilities) }},
	{RouteContract{http.MethodPost, "/admin/v1/providers"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CreateProvider) }},
	{RouteContract{http.MethodPut, "/admin/v1/providers/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.UpdateProvider) }},
	{RouteContract{http.MethodDelete, "/admin/v1/providers/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteProvider) }},
	{RouteContract{http.MethodPost, "/admin/v1/providers/{id}/test"}, func(h Handler) http.Handler { return http.HandlerFunc(h.TestProviderConnection) }},
	{RouteContract{http.MethodPost, "/admin/v1/providers/{id}/discover-models"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DiscoverProviderModels) }},
	{RouteContract{http.MethodGet, "/admin/v1/credentials"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListCredentials) }},
	{RouteContract{http.MethodPost, "/admin/v1/credentials"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CreateCredential) }},
	{RouteContract{http.MethodPut, "/admin/v1/credentials/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.UpdateCredential) }},
	{RouteContract{http.MethodPost, "/admin/v1/credentials/{id}/rotate"}, func(h Handler) http.Handler { return http.HandlerFunc(h.RotateCredential) }},
	{RouteContract{http.MethodDelete, "/admin/v1/credentials/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteCredential) }},
	{RouteContract{http.MethodPut, "/admin/v1/model-catalog"}, func(h Handler) http.Handler { return http.HandlerFunc(h.PutModelCatalog) }},
	{RouteContract{http.MethodGet, "/admin/v1/ai-hub/models"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetAIHubModels) }},
	{RouteContract{http.MethodGet, "/admin/v1/cost-optimization/recommendations"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetCostRecommendations) }},
	{RouteContract{http.MethodGet, "/admin/v1/model-deployments"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListModelDeployments) }},
	{RouteContract{http.MethodGet, "/admin/v1/model-deployments/health"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListLatestModelDeploymentHealth) }},
	{RouteContract{http.MethodPost, "/admin/v1/model-deployments/health-checks"}, func(h Handler) http.Handler { return http.HandlerFunc(h.TestModelDeployments) }},
	{RouteContract{http.MethodPost, "/admin/v1/model-deployments"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CreateModelDeployment) }},
	{RouteContract{http.MethodPut, "/admin/v1/model-deployments/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.UpdateModelDeployment) }},
	{RouteContract{http.MethodDelete, "/admin/v1/model-deployments/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteModelDeployment) }},
	{RouteContract{http.MethodPost, "/admin/v1/model-deployments/{id}/test"}, func(h Handler) http.Handler { return http.HandlerFunc(h.TestModelDeployment) }},
	{RouteContract{http.MethodGet, "/admin/v1/model-deployments/{id}/health"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListModelDeploymentHealth) }},
	{RouteContract{http.MethodGet, "/admin/v1/model-groups"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListModelGroups) }},
	{RouteContract{http.MethodPost, "/admin/v1/model-groups"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CreateModelGroup) }},
	{RouteContract{http.MethodPut, "/admin/v1/model-groups/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.UpdateModelGroup) }},
	{RouteContract{http.MethodDelete, "/admin/v1/model-groups/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteModelGroup) }},
	{RouteContract{http.MethodGet, "/admin/v1/model-groups/{id}/routing-settings"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetModelGroupRouting) }},
	{RouteContract{http.MethodPut, "/admin/v1/model-groups/{id}/routing-settings"}, func(h Handler) http.Handler { return http.HandlerFunc(h.UpdateModelGroupRouting) }},
	{RouteContract{http.MethodGet, "/admin/v1/guardrail-policies"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListGuardrailPolicies) }},
	{RouteContract{http.MethodGet, "/admin/v1/anonymizer/rules"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListAnonymizerRules) }},
	{RouteContract{http.MethodPut, "/admin/v1/guardrail-policies/{name}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.UpdateGuardrailPolicy) }},
	{RouteContract{http.MethodGet, "/admin/v1/policy-attachments"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListPolicyAttachments) }},
	{RouteContract{http.MethodPost, "/admin/v1/policy-attachments/resolve"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ResolvePolicyAttachments) }},
	{RouteContract{http.MethodPut, "/admin/v1/policy-attachments/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.PutPolicyAttachment) }},
	{RouteContract{http.MethodDelete, "/admin/v1/policy-attachments/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeletePolicyAttachment) }},
	{RouteContract{http.MethodGet, "/admin/v1/tags"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListTags) }},
	{RouteContract{http.MethodPut, "/admin/v1/tags/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.PutTag) }},
	{RouteContract{http.MethodDelete, "/admin/v1/tags/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteTag) }},
	{RouteContract{http.MethodPost, "/admin/v1/compliance/check"}, func(h Handler) http.Handler { return http.HandlerFunc(h.CheckCompliance) }},
	{RouteContract{http.MethodGet, "/admin/v1/guardrails/monitor"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetGuardrailMonitor) }},
	{RouteContract{http.MethodGet, "/admin/v1/cache/diagnostics"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetCacheDiagnostics) }},
	{RouteContract{http.MethodGet, "/admin/v1/logging/destinations"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListLoggingDestinations) }},
	{RouteContract{http.MethodPut, "/admin/v1/logging/destinations/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.PutLoggingDestination) }},
	{RouteContract{http.MethodDelete, "/admin/v1/logging/destinations/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteLoggingDestination) }},
	{RouteContract{http.MethodPost, "/admin/v1/logging/destinations/{id}/test"}, func(h Handler) http.Handler { return http.HandlerFunc(h.TestLoggingDestination) }},
	{RouteContract{http.MethodGet, "/admin/v1/tool-policies"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListToolPolicies) }},
	{RouteContract{http.MethodPut, "/admin/v1/tool-policies/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.PutToolPolicy) }},
	{RouteContract{http.MethodDelete, "/admin/v1/tool-policies/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteToolPolicy) }},
	{RouteContract{http.MethodGet, "/admin/v1/agent-profiles"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListAgentProfiles) }},
	{RouteContract{http.MethodPut, "/admin/v1/agent-profiles/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.PutAgentProfile) }},
	{RouteContract{http.MethodDelete, "/admin/v1/agent-profiles/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteAgentProfile) }},
	{RouteContract{http.MethodGet, "/admin/v1/mcp/servers"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListMCPServers) }},
	{RouteContract{http.MethodPut, "/admin/v1/mcp/servers/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.UpdateMCPServer) }},
	{RouteContract{http.MethodDelete, "/admin/v1/mcp/servers/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteMCPServer) }},
	{RouteContract{http.MethodGet, "/admin/v1/mcp/toolsets"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListMCPToolsets) }},
	{RouteContract{http.MethodPut, "/admin/v1/mcp/toolsets/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.UpdateMCPToolset) }},
	{RouteContract{http.MethodDelete, "/admin/v1/mcp/toolsets/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteMCPToolset) }},
	{RouteContract{http.MethodGet, "/admin/v1/projects"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListProjects) }},
	{RouteContract{http.MethodGet, "/admin/v1/projects/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetProject) }},
	{RouteContract{http.MethodPut, "/admin/v1/projects/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.PutProject) }},
	{RouteContract{http.MethodDelete, "/admin/v1/projects/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteProject) }},
	{RouteContract{http.MethodGet, "/admin/v1/access-groups"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListAccessGroups) }},
	{RouteContract{http.MethodGet, "/admin/v1/access-groups/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.GetAccessGroup) }},
	{RouteContract{http.MethodPut, "/admin/v1/access-groups/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.PutAccessGroup) }},
	{RouteContract{http.MethodDelete, "/admin/v1/access-groups/{id}"}, func(h Handler) http.Handler { return http.HandlerFunc(h.DeleteAccessGroup) }},
	{RouteContract{http.MethodGet, "/admin/v1/audit/events"}, func(h Handler) http.Handler { return http.HandlerFunc(h.ListAuditEvents) }},
}

func DocumentedRoutes() []RouteContract {
	routes := make([]RouteContract, len(gatewayRoutes))
	for index, route := range gatewayRoutes {
		routes[index] = route.RouteContract
	}
	return append(routes, generateRoutes...)
}

func Routes(handler Handler) http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("POST /v1beta/models/{modelAction}", handler.GenerateContent)
	for _, route := range gatewayRoutes {
		h := route.handler(handler)
		if handler.adminState != nil && isDurableAdminStateRoute(route.Path) {
			h = handler.adminState.Wrap(h, isDurableAdminStateMutation(route.Method, route.Path))
		}
		mux.Handle(route.Method+" "+route.Path, h)
	}
	if handler.apiDocs.enabled {
		registerAPIDocs(mux, handler.apiDocs)
	}
	if handler.adminUI {
		registerAdminUI(mux)
	}
	observed := observabilityMiddleware(handler.metrics, browserSSOAuthMiddleware(handler.browserSSO, mux))
	return otelhttp.NewHandler(observed, "ai-gateway.http",
		otelhttp.WithFilter(func(r *http.Request) bool {
			return !isInfrastructurePath(r.URL.Path)
		}),
		otelhttp.WithSpanNameFormatter(func(_ string, r *http.Request) string {
			return metricMethod(r.Method) + " " + metricPath(r.URL.Path)
		}),
	)
}
