apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.fullname" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.username | quote }}
  password: {{ .Values.password | quote }}
