import type { ResourceConfig } from "../components/ResourcePage";
import type { Field } from "../components/ResourceForm";

const id: Field = { key: "id", label: "ID", required: true, readOnlyOnEdit: true };
const name: Field = { key: "name", label: "Name", required: true };
const description: Field = { key: "description", label: "Description", type: "textarea" };
const enabled: Field = { key: "enabled", label: "Enabled", type: "boolean", defaultValue: true };
const columns = (...entries: Array<[string, string]>) => entries.map(([key, label]) => ({ key, label }));

export const resourceConfigs: Record<string, ResourceConfig> = {
  keys: {
    eyebrow: "Access control", title: "Virtual keys", description: "Issue scoped, revocable gateway credentials. Newly issued and rotated tokens are displayed once.", listPath: "/admin/v1/keys?limit=100", createPath: "/admin/v1/keys", createMethod: "POST", itemPath: (value) => `/admin/v1/keys/${encodeURIComponent(value)}`, deletePath: (value) => `/admin/v1/keys/${encodeURIComponent(value)}`, columns: columns(["id", "Key"], ["alias", "Alias"], ["status", "Status"], ["allowed_models", "Models"], ["allowed_tools", "Tools"], ["rate_limit_rpm", "RPM"], ["rate_limit_tpm", "TPM"]), fields: [{ key: "alias", label: "Alias", required: true }, description, { key: "tags", label: "Tags", type: "csv" }, { key: "user_id", label: "User ID" }, { key: "team_id", label: "Team ID" }, { key: "roles", label: "Roles", type: "csv" }, { key: "allowed_models", label: "Allowed models", type: "csv" }, { key: "allowed_tools", label: "Allowed tools", type: "csv" }, { key: "rate_limit_rpm", label: "RPM", type: "number" }, { key: "rate_limit_tpm", label: "TPM", type: "number" }], operations: [{ label: "Rotate", path: (row) => `/admin/v1/keys/${encodeURIComponent(String(row.id))}/rotate`, body: (row) => ({ alias: row.alias, description: row.description, tags: row.tags || [], user_id: row.user_id, team_id: row.team_id, roles: row.roles || [], allowed_models: row.allowed_models || [], allowed_tools: row.allowed_tools || [], rate_limit_rpm: row.rate_limit_rpm || 0, rate_limit_tpm: row.rate_limit_tpm || 0 }) }, { label: "Enable", path: (row) => `/admin/v1/keys/${encodeURIComponent(String(row.id))}/enable` }, { label: "Disable", path: (row) => `/admin/v1/keys/${encodeURIComponent(String(row.id))}/disable` }]
  },
  users: {
    eyebrow: "Identity", title: "Users", description: "Manage directory identities exposed by the auth service.", listPath: "/admin/v1/users?limit=100", itemPath: (value) => `/admin/v1/users/${encodeURIComponent(value)}`, columns: columns(["id", "User"], ["name", "Name"], ["email", "Email"], ["roles", "Roles"], ["team_ids", "Teams"], ["status", "Status"]), fields: [id, { key: "email", label: "Email", required: true }, name, { key: "roles", label: "Roles", type: "csv" }, { key: "status", label: "Status", type: "select", options: ["active", "disabled"], defaultValue: "active" }]
  },
  teams: {
    eyebrow: "Identity", title: "Teams", description: "Manage teams and their ownership boundaries.", listPath: "/admin/v1/teams?limit=100", itemPath: (value) => `/admin/v1/teams/${encodeURIComponent(value)}`, columns: columns(["id", "Team"], ["name", "Name"], ["description", "Description"], ["member_count", "Members"], ["status", "Status"]), fields: [id, name, description, { key: "status", label: "Status", type: "select", options: ["active", "disabled"], defaultValue: "active" }]
  },
  organizations: {
    eyebrow: "Identity", title: "Organizations", description: "Group teams into administrative organizations.", listPath: "/admin/v1/organizations?limit=100", itemPath: (value) => `/admin/v1/organizations/${encodeURIComponent(value)}`, columns: columns(["id", "Organization"], ["name", "Name"], ["description", "Description"], ["team_ids", "Teams"], ["status", "Status"]), fields: [id, name, description, { key: "status", label: "Status", type: "select", options: ["active", "disabled"], defaultValue: "active" }]
  },
  projects: {
    eyebrow: "Ownership", title: "Projects", description: "Assign gateway resources to teams and environments.", listPath: "/admin/v1/projects", itemPath: (value) => `/admin/v1/projects/${encodeURIComponent(value)}`, deletePath: (value) => `/admin/v1/projects/${encodeURIComponent(value)}`, columns: columns(["id", "Project"], ["name", "Name"], ["team_id", "Team"], ["tags", "Tags"], ["enabled", "Status"]), fields: [id, name, description, { key: "team_id", label: "Owner team ID" }, { key: "tags", label: "Tags", type: "csv" }, enabled]
  },
  accessGroups: {
    eyebrow: "Access control", title: "Access groups", description: "Reusable permission templates for virtual keys.", listPath: "/admin/v1/access-groups", itemPath: (value) => `/admin/v1/access-groups/${encodeURIComponent(value)}`, deletePath: (value) => `/admin/v1/access-groups/${encodeURIComponent(value)}`, columns: columns(["id", "Group"], ["name", "Name"], ["project_id", "Project"], ["allowed_models", "Models"], ["allowed_tools", "Tools"], ["enabled", "Status"]), fields: [id, name, description, { key: "project_id", label: "Project ID" }, { key: "allowed_models", label: "Allowed models", type: "csv" }, { key: "allowed_tools", label: "Allowed tools", type: "csv" }, { key: "tags", label: "Tags", type: "csv" }, enabled]
  },
  providers: {
    eyebrow: "Connectivity", title: "Providers", description: "Manage upstream provider endpoints independently from credentials.", managedTable: true, createLabel: "Create Provider", listPath: "/admin/v1/providers", createPath: "/admin/v1/providers", createMethod: "POST", itemPath: (value) => `/admin/v1/providers/${encodeURIComponent(value)}`, deletePath: (value) => `/admin/v1/providers/${encodeURIComponent(value)}`, columns: columns(["id", "Provider"], ["type", "Type"], ["base_url", "Base URL"], ["enabled", "Status"]), fields: [id, { key: "type", label: "Type", type: "select", options: ["ollama", "openai", "openai-compatible", "anthropic", "demo"], defaultValue: "openai-compatible" }, { key: "base_url", label: "Base URL", required: true }, enabled], operations: [{ label: "Test", path: (row) => `/admin/v1/providers/${encodeURIComponent(String(row.id))}/test`, body: () => ({}) }, { label: "Discover models", path: (row) => `/admin/v1/providers/${encodeURIComponent(String(row.id))}/discover-models`, body: () => ({}) }]
  },
  credentials: {
    eyebrow: "Secret vault", title: "Credentials", description: "Write-only provider credentials encrypted at rest.", managedTable: true, createLabel: "Create Credential", listPath: "/admin/v1/credentials", createPath: "/admin/v1/credentials", createMethod: "POST", itemPath: (value) => `/admin/v1/credentials/${encodeURIComponent(value)}`, deletePath: (value) => `/admin/v1/credentials/${encodeURIComponent(value)}`, columns: columns(["id", "Credential"], ["provider_id", "Provider"], ["description", "Description"], ["updated_at", "Updated"]), fields: [id, { key: "provider_id", label: "Provider", type: "reference", reference: { path: "/admin/v1/providers", labelKeys: ["type", "base_url"] } }, description, { key: "secret", label: "Secret", type: "password", required: true }]
  },
  deployments: {
    eyebrow: "Runtime routing", title: "Deployments", description: "Provider/model endpoints with retry, admission and cooldown controls.", listPath: "/admin/v1/model-deployments", createPath: "/admin/v1/model-deployments", createMethod: "POST", itemPath: (value) => `/admin/v1/model-deployments/${encodeURIComponent(value)}`, deletePath: (value) => `/admin/v1/model-deployments/${encodeURIComponent(value)}`, columns: columns(["id", "Deployment"], ["provider_id", "Provider"], ["models", "Public models"], ["upstream_model", "Upstream"], ["priority", "Priority"], ["weight", "Weight"], ["runtime_state", "Runtime"], ["enabled", "Status"]), fields: [id, { key: "provider_id", label: "Provider", type: "reference", required: true, reference: { path: "/admin/v1/providers", labelKeys: ["type", "base_url"] } }, { key: "credential_id", label: "Credential", type: "reference", reference: { path: "/admin/v1/credentials", labelKeys: ["description"], filter: { fieldKey: "provider_id", recordKey: "provider_id" } } }, { key: "models", label: "Public models", type: "reference-multi", required: true, reference: { path: "/admin/v1/model-catalog", collectionKey: "models", valueKey: "model", labelKeys: ["provider", "capabilities"] } }, { key: "upstream_model", label: "Upstream model" }, { key: "capabilities", label: "Capabilities", type: "csv" }, { key: "priority", label: "Priority", type: "number" }, { key: "weight", label: "Weight", type: "number", defaultValue: 1 }, { key: "max_retries", label: "Max retries", type: "number" }, { key: "request_timeout_ms", label: "Request timeout (ms)", type: "number" }, { key: "cooldown_after_failures", label: "Failures before cooldown", type: "number" }, { key: "cooldown_seconds", label: "Cooldown seconds", type: "number" }, { key: "max_parallel_requests", label: "Max parallel requests", type: "number" }, { key: "queue_capacity", label: "Queue capacity", type: "number" }, { key: "queue_timeout_ms", label: "Queue timeout (ms)", type: "number" }, { key: "guardrail_policy", label: "Guardrail policy" }, enabled], operations: [{ label: "Test", path: (row) => `/admin/v1/model-deployments/${encodeURIComponent(String(row.id))}/test`, body: () => ({}) }, { label: "Health", method: "GET", path: (row) => `/admin/v1/model-deployments/${encodeURIComponent(String(row.id))}/health?limit=20` }]
  },
  modelGroups: {
    eyebrow: "Routing", title: "Model groups", description: "Stable public model aliases backed by ordered deployments.", managedTable: true, createLabel: "Create Model Group", listPath: "/admin/v1/model-groups", createPath: "/admin/v1/model-groups", createMethod: "POST", itemPath: (value) => `/admin/v1/model-groups/${encodeURIComponent(value)}`, deletePath: (value) => `/admin/v1/model-groups/${encodeURIComponent(value)}`, columns: columns(["id", "Public model"], ["deployment_ids", "Deployments"], ["strategy", "Strategy"], ["enabled", "Status"]), fields: [id, { key: "deployment_ids", label: "Deployments", type: "reference-multi", required: true, reference: { path: "/admin/v1/model-deployments", labelKeys: ["provider_id", "upstream_model"] } }, { key: "strategy", label: "Strategy", type: "select", options: ["weighted", "adaptive"], defaultValue: "weighted" }, enabled]
  },
  guardrails: {
    eyebrow: "Compliance", title: "Guardrail policies", description: "Runtime DLP and AV policy configuration.", listPath: "/admin/v1/guardrail-policies", itemPath: (value) => `/admin/v1/guardrail-policies/${encodeURIComponent(value)}`, idKey: "name", columns: columns(["name", "Policy"], ["description", "Description"], ["dlp", "DLP"], ["av", "AV"], ["enabled", "Status"]), fields: [{ key: "name", label: "Policy name", required: true, readOnlyOnEdit: true }, description, { key: "dlp", label: "DLP", type: "boolean", defaultValue: true }, { key: "av", label: "Antivirus", type: "boolean" }, enabled]
  },
  logging: {
    eyebrow: "Observability", title: "Logging destinations", description: "Metadata-only callbacks with write-only bearer secrets.", listPath: "/admin/v1/logging/destinations", itemPath: (value) => `/admin/v1/logging/destinations/${encodeURIComponent(value)}`, deletePath: (value) => `/admin/v1/logging/destinations/${encodeURIComponent(value)}`, columns: columns(["id", "Destination"], ["name", "Name"], ["type", "Type"], ["url", "URL"], ["event_types", "Events"], ["secret_configured", "Secret"], ["enabled", "Status"]), fields: [id, name, { key: "type", label: "Type", type: "select", options: ["webhook"], defaultValue: "webhook" }, { key: "url", label: "HTTPS URL", required: true }, { key: "event_types", label: "Events", type: "csv", defaultValue: ["request_outcome"] }, { key: "secret", label: "Bearer secret", type: "password" }, enabled], operations: [{ label: "Test", path: (row) => `/admin/v1/logging/destinations/${encodeURIComponent(String(row.id))}/test`, body: () => ({}) }]
  },
  toolPolicies: {
    eyebrow: "Tool governance", title: "Tool policies", description: "Reusable allow, deny and approval policies.", listPath: "/admin/v1/tool-policies", itemPath: (value) => `/admin/v1/tool-policies/${encodeURIComponent(value)}`, deletePath: (value) => `/admin/v1/tool-policies/${encodeURIComponent(value)}`, columns: columns(["id", "Policy"], ["name", "Name"], ["allowed_tools", "Allowed"], ["denied_tools", "Denied"], ["approval_required", "Approval"], ["enabled", "Status"]), fields: [id, name, description, { key: "allowed_tools", label: "Allowed tools", type: "csv", required: true }, { key: "denied_tools", label: "Denied tools", type: "csv" }, { key: "approval_required", label: "Approval required", type: "csv" }, { key: "max_tool_calls", label: "Max tool calls", type: "number", defaultValue: 8 }, enabled]
  },
  agents: {
    eyebrow: "Agent governance", title: "Agent profiles", description: "External runtime templates without prompt or memory storage.", listPath: "/admin/v1/agent-profiles", itemPath: (value) => `/admin/v1/agent-profiles/${encodeURIComponent(value)}`, deletePath: (value) => `/admin/v1/agent-profiles/${encodeURIComponent(value)}`, columns: columns(["id", "Profile"], ["name", "Name"], ["model", "Model"], ["tool_policy_id", "Policy"], ["max_iterations", "Iterations"], ["enabled", "Status"]), fields: [id, name, description, { key: "model", label: "Model", required: true }, { key: "tool_policy_id", label: "Tool policy ID", required: true }, { key: "instructions_template_id", label: "Instructions template ID" }, { key: "max_iterations", label: "Max iterations", type: "number", defaultValue: 8 }, { key: "tags", label: "Tags", type: "csv" }, enabled]
  },
  mcpServers: {
    eyebrow: "Tool governance", title: "MCP servers", description: "Approved HTTPS MCP endpoints without embedded credentials.", listPath: "/admin/v1/mcp/servers", itemPath: (value) => `/admin/v1/mcp/servers/${encodeURIComponent(value)}`, columns: columns(["id", "Server"], ["label", "Label"], ["server_url", "URL"], ["transport", "Transport"], ["tools", "Tools"], ["enabled", "Status"]), fields: [id, { key: "label", label: "Label", required: true }, description, { key: "server_url", label: "HTTPS server URL", required: true }, { key: "transport", label: "Transport", type: "select", options: ["streamable-http", "sse"], defaultValue: "streamable-http" }, { key: "tools", label: "Tool identifiers", type: "csv" }, enabled]
  },
  mcpToolsets: {
    eyebrow: "Tool governance", title: "MCP toolsets", description: "Permission bundles referencing canonical tool identifiers.", listPath: "/admin/v1/mcp/toolsets", itemPath: (value) => `/admin/v1/mcp/toolsets/${encodeURIComponent(value)}`, columns: columns(["id", "Toolset"], ["name", "Name"], ["tools", "Tools"], ["enabled", "Status"]), fields: [id, name, description, { key: "tools", label: "Tools", type: "csv", required: true }, enabled]
  },
  budgets: {
    eyebrow: "Financial controls", title: "Budgets", description: "Spend and token limits enforced by scope and period.", listPath: "/admin/v1/budgets", createPath: "/admin/v1/budgets", createMethod: "POST", itemPath: (value) => `/admin/v1/budgets/${encodeURIComponent(value)}`, deletePath: (value) => `/admin/v1/budgets/${encodeURIComponent(value)}`, columns: columns(["id", "Budget"], ["scope_type", "Scope"], ["scope_id", "Subject"], ["max_cost", "Cost limit"], ["max_tokens", "Token limit"], ["enabled", "Status"]), fields: [{ key: "scope_type", label: "Scope type", type: "select", options: ["global", "user", "team", "key"], defaultValue: "global" }, { key: "scope_id", label: "Scope ID" }, { key: "period", label: "Period", type: "select", options: ["day", "month"], defaultValue: "month" }, { key: "max_cost", label: "Maximum cost", type: "number" }, { key: "max_tokens", label: "Maximum tokens", type: "number" }, { key: "currency", label: "Currency", defaultValue: "USD" }, enabled]
  },
  requestLogs: {
    eyebrow: "Observability", title: "Request logs", description: "Bounded operational metadata without prompt or response content.", listPath: "/admin/v1/request-logs", columns: columns(["occurred_at", "Time"], ["request_id", "Request"], ["session_id", "Session"], ["status", "Status"], ["model", "Public model"], ["upstream_model", "Upstream model"], ["provider", "Provider"], ["total_tokens", "Tokens"], ["latency_ms", "Latency"], ["cost", "Cost"])
  },
  audit: {
    eyebrow: "Governance", title: "Audit log", description: "Administrative mutations and their outcomes.", listPath: "/admin/v1/audit/events", columns: columns(["occurred_at", "Time"], ["action", "Action"], ["target_type", "Type"], ["target_id", "Target"], ["actor_id", "Actor"], ["outcome", "Outcome"])
  }
};
