#!/usr/bin/env python3
"""Update documentation inventories from tracked contracts, without dependencies."""

import argparse
from collections import defaultdict
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]


def api_index():
    spec = (ROOT / "repos/gateway/api/openapi.yaml").read_text()
    operations = []
    path = method = operation_id = None
    tag = "Other"

    def flush():
        if method:
            if not operation_id:
                raise ValueError(f"Missing operationId: {method} {path}")
            operations.append((tag, method.upper(), path, operation_id))

    for line in spec.split("\npaths:\n", 1)[1].split("\ncomponents:", 1)[0].splitlines():
        match = re.fullmatch(r"  (/\S+):", line)
        if match:
            flush()
            path, method, operation_id, tag = match[1], None, None, "Other"
        elif re.fullmatch(r"    (get|post|put|patch|delete|head|options):", line):
            flush()
            method, operation_id, tag = line.strip()[:-1], None, "Other"
        elif method:
            match = re.fullmatch(r"      operationId: (\S+)", line)
            if match:
                operation_id = match[1]
            match = re.fullmatch(r"      tags: \[([^\]]+)\]", line)
            if match:
                tag = match[1].split(",")[0].strip()
    flush()
    routes = (ROOT / "repos/gateway/internal/gateway/routes.go").read_text()
    registered = {(m.upper(), p) for m, p in re.findall(
        r'RouteContract\{http\.Method(\w+), "([^"]+)"\}', routes)}
    generate = (ROOT / "repos/gateway/internal/gateway/generate.go").read_text()
    registered.update((m.upper(), p) for m, p in re.findall(
        r'\{http\.Method(\w+), "([^"]+)"\}', generate))
    documented = {(method, path) for _, method, path, _ in operations}
    if registered != documented or len(documented) != len(operations):
        raise ValueError(f"Route/OpenAPI mismatch: {registered ^ documented}")
    lines = [
        "# Индекс HTTP API", "",
        "<!-- Generated by scripts/update-documentation.py; edit OpenAPI, then regenerate. -->", "",
        f"Все {len(operations)} HTTP-операции ({len({p for _, _, p, _ in operations})} путей) "
        "из [OpenAPI](../repos/gateway/api/openapi.yaml), сверенные с "
        "[route contract](../repos/gateway/internal/gateway/routes.go).", "",
        "Этот индекс помогает найти операцию. Payload, security requirements, статусы и "
        "ограничения находятся в OpenAPI; наличие route не означает поддержку каждым provider.", "",
        "Порядок inference, capabilities и provider ограничения: [Inference API](inference.md). "
        "Browser SSO: [SSO settings](admin-sso-settings.md); tenant scope: "
        "[Organization identity](organization-identity.md). Межсервисные API Auth/Billing/DLP/AV "
        "описаны в README компонентов и не являются публичными Gateway routes.", "",
    ]
    grouped = defaultdict(list)
    for tag, method, path, operation_id in operations:
        grouped[tag].append((path, method, operation_id))
    for tag in sorted(grouped):
        lines += [f"## {tag}", "", "| Method | Path | Operation ID |",
                  "| --- | --- | --- |"]
        for path, method, operation_id in sorted(grouped[tag]):
            lines.append(f"| `{method}` | `{path}` | `{operation_id}` |")
        lines.append("")
    return "\n".join(lines)


def environment_reference():
    lines = [
        "# Индекс переменных окружения", "",
        "<!-- Generated by scripts/update-documentation.py; edit Go sources, then regenerate. -->", "",
        "Индекс буквальных environment names, читаемых production Go-кодом каждого сервиса. "
        "Значения окружения, credentials и developer files генератор не читает. "
        "Переменная может быть legacy, условной или provider-specific; её наличие здесь "
        "не означает включённую функцию.", "",
        "Defaults, диапазоны, required flags и взаимосвязи: [Конфигурация](configuration.md) "
        "и README сервиса. SSO compatibility: [SSO settings](admin-sso-settings.md); "
        "Python stack и Docling queue: [Document processing](document-processing.md). "
        "Это индекс Go-конфигурации, а не перечень всех container/Helm options. "
        "Динамически вычисляемые имена нужно проверять в соответствующем коде.", "",
    ]
    pattern = re.compile(r'\b([\w.]+)\(\s*"([A-Z][A-Z0-9_]{3,})"')
    for service in ("gateway", "auth", "billing", "anonymizer", "dlp", "av"):
        references = defaultdict(set)
        for source in sorted((ROOT / "repos" / service).rglob("*.go")):
            if (source.name.endswith("_test.go")
                    or any(part in {"vendor", "node_modules", ".git"} for part in source.parts)):
                continue
            for fn, name in pattern.findall(source.read_text()):
                if "env" in fn.lower():
                    references[name].add(source.relative_to(ROOT).as_posix())
        lines += [f"## {service} ({len(references)} names)", "",
                  f"[Component README](../repos/{service}/README.md).", "",
                  "| Variable | Code reference |", "| --- | --- |"]
        for name, paths in sorted(references.items()):
            links = ", ".join(f"[{path.rsplit('/', 1)[-1]}](../{path})" for path in sorted(paths))
            lines.append(f"| `{name}` | {links} |")
        lines.append("")
    return "\n".join(lines)


def check_ui_routes():
    source = (ROOT / "repos/gateway/ui/src/app/routes.tsx").read_text()
    source = source.split("export const appRoutes: AppRoute[] = [", 1)[1].split("\n];", 1)[0]
    expected = {}
    for line in source.splitlines():
        path = re.search(r'path: "([^"]+)"', line)
        if path and "navigation: false" not in line:
            capability = re.search(r'capability: "([^"]+)"', line)
            expected[path[1]] = capability[1] if capability else "admin"
    navigation = (ROOT / "repos/gateway/ui/src/app/navigation.ts").read_text()
    navigation = navigation.split("export const navigationSections: NavigationSection[] = [", 1)[1].split("\n];", 1)[0]
    links = re.findall(r'"(/[^\"]+)"', navigation)
    documented = re.findall(r'\| `(/[^`]+)` \| `([^`]+)` \|', (ROOT / "docs/admin-ui.md").read_text())
    if (dict(documented) != expected or len(documented) != len(expected)
            or set(links) != set(expected) or len(links) != len(expected)):
        raise ValueError("UI routes/capabilities differ from docs/admin-ui.md or navigation.ts")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if inventories need regeneration")
    args = parser.parse_args()
    check_ui_routes()
    outdated = []
    for name, render in (("api-index.md", api_index), ("environment-reference.md", environment_reference)):
        target = ROOT / "docs" / name
        expected = render()
        if args.check:
            if not target.exists() or target.read_text() != expected:
                outdated.append(name)
        else:
            target.write_text(expected)
    if outdated:
        print("Regenerate with python3 scripts/update-documentation.py: " + ", ".join(outdated), file=sys.stderr)
        return 1
    print("Documentation inventories are current" if args.check else "Documentation inventories updated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
