replicaCount: 1

image:
  repository: redis
  tag: 7-alpine
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 6379

persistence:
  enabled: true
  size: 1Gi
  accessModes:
    - ReadWriteOnce

resources: {}

nameOverride: ""
fullnameOverride: ""
